### ISSUE TITLE
Allow filtering by direction of line busses

### ISSUE THREAD

**Issue by GiovaGa** [Stypox/tridenta#7]
It would be really nice when viewing a line, to be able to filter the availible trips by direction.

I think that for this function a button next to the "favorite" button could be an option.

**Comment by Stypox** [comment]
This was implemented in https://github.com/Stypox/tridenta/commit/a75e1e60cdba69d193ffee6d2507950f5fb1a844, however the implementation might be a bit buggy, because the code is pretty complex. Here is a testing APK if you want to try it out: [app-debug.zip](https://github.com/Stypox/tridenta/files/13329293/app-debug.zip)
